name: CI for main branch

on:
  push:
    branches: [main]

jobs:
  test-go:
    uses: ./.github/workflows/wf-test-go.yml
  
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: 364898
          private-key: ${{ secrets.ARTHUR1_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: Songmu/tagpr@35daec35e8e3172806c763d8f196e6434fd44fbd # v1.5.2
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
