name: CI for pull request

on:
  pull_request:

jobs:
  test-go:
    uses: ./.github/workflows/wf-test-go.yml

  build-container:
    uses: ./.github/workflows/wf-build-container.yml
    secrets: inherit
    with:
      needs-push: true
