name: test-go

on:
  workflow_call:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          args: --timeout=10m
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: stable
      - run: |
          go install github.com/mfridman/tparse@latest
      - run: |
          set -o pipefail
          go test ./... -cover -json | tee ./go-test.out | tparse -all
      - if: always()
        run: |
          tparse -file ./go-test.out -format markdown >> "$GITHUB_STEP_SUMMARY"
